apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: project-testing
spec:
  selector:
    matchLabels:
      app: httpd
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: image-registry.openshift-image-registry.svc:5000/project-testing/backend-api:1.1
          resources:
            requests:
              cpu: "250m"
              memory: "1000Mi"
            limits:
              cpu: "500m"
              memory: "2000Mi"
          ports:
            - containerPort: 8081
