apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: project-testing
spec:
  selector:
    matchLabels:
      app: httpd
    replicas: 1
    template:
      metadata:
        labels:
          app: httpd
      spec:
        containers:
          - name: httpd
            image: xxx
            ports:
              - containerPort: 8080